
apiVersion: v1
kind: Service
metadata:
  name: dockerproj2-service
spec:
  type: NodePort   # You can change this to 'LoadBalancer' on EKS
  selector:
    app: dockerproject
  ports:
    - protocol: TCP
      port: 8080          # Service port (inside cluster)
      targetPort: 8080    # Container port
      nodePort: 30080     # External port on Minikube node (optional, or let K8s assign automatically)
